POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "achal",
  "name": "achal",
  "password": "123456",
  "gender": "male",
  "location": "aswapuram"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "achal",
  "password": "1234567"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "achal",
  "oldPassword": "123456",
  "newPassword": "1234567"
}